Added CSS to Leadership Team section
Code-For-Chicago/code-for-chicago-jekyll pull request #148
Opened 2021-05-14 23:40 UTC by Yeen125

Added the CSS via SASS to the Leadership Team section of the About page. Also made minor changes to the HTML code to better fit the Figma mock-up.

2021-05-15 21:05 UTC, daleinen7 requested changes
Good start. Just a few notes and then the design is a little off. 
<img width="1372" alt="pr" src="https://user-images.githubusercontent.com/6326891/118378116-0c8a2000-b597-11eb-8c67-5046ca35985f.png">
![design](https://user-images.githubusercontent.com/6326891/118378121-13189780-b597-11eb-81dd-c98175e356bf.png)
Looks like when it's two rows, the bottom two are spread further apart than in the design. 
<img width="450" alt="Screen Shot 2021-05-15 at 3 54 37 PM" src="https://user-images.githubusercontent.com/6326891/118378136-2d527580-b597-11eb-91db-af7ed4e4bfac.png">
And then the heading part doesn't look like it's the same size as the "Work with Us" section that it's based off of.

2021-05-17 21:35 UTC, jrapala requested changes
Is your other PR, https://github.com/Code-For-Chicago/code-for-chicago-jekyll/pull/139, no longer relevant? This seems to use a lot of the same code you have there.

If so, please close the other PR.

2021-05-17 21:35 UTC, jrapala commented on scss/main.scss
> +    color: #333;
Please use a variable

2021-05-17 21:35 UTC, jrapala commented on pages/about.html
> +            <p>Paternships Co-Lead</p>
Typo

2021-06-14 20:47 UTC, closed without merging