Share bar
Code-For-Chicago/code-for-chicago-jekyll pull request #157
Opened 2021-05-26 02:31 UTC by daleinen7

This is a draft showing both the custom boxes and the built in boxes. 

Obviously the styling of each needs some adjustments so our imaginations might need to be employed to see the possible final outcome.

2021-06-30 01:17 UTC, jrapala commented
The Facebook button is missing a focus style. Can we please add?

2021-06-30 01:17 UTC, jrapala requested changes
The Facebook button is missing a focus style. Can we please add?

2021-06-30 13:29 UTC, daleinen7 commented
> The Facebook button is missing a focus style. Can we please add?

It seems like the answer is no. Looks like we'll have to go the route of getting a Facebook App ID. I'll check with Ryan about making that happen.

2021-07-16 01:04 UTC, jrapala approved these changes

2021-07-16 13:41 UTC, merged