Nav bar
Code-For-Chicago/code-for-chicago-jekyll pull request #160
Opened 2021-06-09 05:16 UTC by daleinen7

[ticket](https://trello.com/c/xorZwrUa/88-develop-navigation-bar)

2021-06-10 00:11 UTC, jrapala requested changes
Good job! Left a few comments, mostly some accessibility tips. There also seems to be a border missing on the mobile menu:

<img width="244" alt="Screen Shot 2021-06-09 at 6 45 02 PM" src="https://user-images.githubusercontent.com/9326234/121443520-401c5800-c953-11eb-83f8-1464c0d6c62e.png">

2021-06-10 00:11 UTC, jrapala commented on _includes/navbar-w-links.html
> +	<button onClick="toggleMenu()" class="menu-icon"><img src="/images/hamburger-open-menu.svg" alt="open menu"></button>
"Open Menu" remains the same whether it's a hamburger icon or an x icon
I also suggest we add an aria-label to the button instead and add aria-hidden to the img, and use aria-expanded to communicate if the menu is open or closed

2021-06-10 18:03 UTC, daleinen7 commented on scss/main.scss
> +.prevent-scrolling {
Might be more of a designer question if my solution works or not but let me know what you think.

2021-06-10 18:06 UTC, daleinen7 commented on _includes/navbar-w-links.html
> +<nav class="mobile-nav"></nav>
I was a little unclear on the best solution so let me know what you think.

2021-06-14 21:10 UTC, jrapala requested changes
Just two small a11y-related requests

2021-06-14 21:10 UTC, jrapala commented on js/nav.js
> +    ? 'open'
Let's do "open menu" and "close menu" instead. It's not clear it's a menu just yet.

2021-06-14 21:10 UTC, jrapala commented on _includes/navbar-w-links.html
> +	<button aria-label="open" onClick="toggleMenu()" class="menu-icon"><img src="/images/hamburger-open-menu.svg" alt="open menu" aria-hidden="true"></button>
Just an FYI, if there is an `aria-hidden`, the `alt` will not be read (so the `alt` isn't really necessary here)

2021-06-14 21:43 UTC, jrapala submitted a review, later dismissed

2021-06-16 02:56 UTC, merged